### ISSUE TITLE
How to discover devices in all Vlans?

### ISSUE THREAD

**Issue by KaloyanR** [dmroeder/pylogix#111]
Is there a way to discover devices in  differents subnets?
or with a list of addresses not broadcaast msg?

**Comment by dmroeder** [comment]
There was a related discussion going on in issue #93

**Comment by KaloyanR** [comment]
ok, thanks
maybe broadcast msg is not good idea, but can I ask all devices one by one with a list of my IPs something  like for loop to present themselves:
IP, Product Name + Product Id + Vendor/Device ID ect.

**Comment by dmroeder** [comment]
I recently added GetDeviceProperties() that will get the properties of a device a particular IP address:

```
from pylogix import PLC

with PLC('192.168.1.10') as comm:
    ret = comm.GetDeviceProperties().Value
    print(ret.ProductName)
```

**Comment by dmroeder** [comment]
Or for a list of addresses, you might have to do something like this:

```
from pylogix import PLC

addresses = ['192.168.1.10',
             '192.168.1.11']

for address in addresses:
    with PLC(address) as comm:
        ret = comm.GetDeviceProperties().Value
        print(ret.ProductName)
```

**Comment by KaloyanR** [comment]
OK, Thanks I will try it.

Traceback (most recent call last):
  File "C:\MotorService\testpylogix.py", line 14, in <module>
    getDevices()
  File "C:\MotorService\testpylogix.py", line 9, in getDevices
    with PLC(address) as comm:
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by dmroeder** [comment]
I'm guessing address in your code is a list.  If you want help with your code, post it.

**Comment by KaloyanR** [comment]
from pylogix import PLC


def getDevices():

    addresses = ['192.168.11.11',
                 '192.168.11.12']

    for address in addresses:
        with PLC(address) as comm:
            ret = comm.GetDeviceProperties().Value
            print(ret.ProductName)
                        
if __name__ == '__main__':
	getDevices()

**Comment by KaloyanR** [comment]
OK It works. My fault in installation and venv settings.

**Comment by dmroeder** [comment]
Okay, cool. Out of curiosity, what version of python and pylogix are you using?

```
import pylogix
pylogix.__version__
```

**Comment by KaloyanR** [comment]
Pytnon 3.7
pylogix 0.6.2

But there is new problem, in given IP with no device ... error timeout!
How can i pass this to continue to next IP, cause i need kind of network inventory/discovery.

**Comment by kodaman2** [comment]
@KaloyanR In regards to the timeout use a try catch.

https://docs.python.org/3/tutorial/errors.html

**Comment by KaloyanR** [comment]
yes, 'except: pass' works, thanks.

**Comment by kodaman2** [comment]
@KaloyanR np. Normally you'd want to handle the exception. Print to the console or log, or something else. I guess if the IP doesn't exist, there's nothing to do hence why pass might be acceptable in your case.
