### ISSUE TITLE
Write string to Micro800

### ISSUE THREAD

**Issue by bdamori** [dmroeder/pylogix#96]
I just downloaded latest version of Pylogix.  Some how writing string to Micro800 stopped working.  The version I loaded around first of Oct 2019 worked great.

**Comment by dmroeder** [comment]
Thanks for the heads up, I'll take a look when I get back to a computer. It will be a few days.

**Comment by dmroeder** [comment]
In the meantime, can you post the error you get?

**Comment by kodaman2** [comment]
Also please confirm version:

```
python import pylogix pylogix.__version__
```

Also confirm `Micro800` is set to `True` on your script not on `eip.py`. I've seen some users change that value on eip.py and since you mentioned you installed it that could very well be the issue.

**Comment by bdamori** [comment]
Sorry I copied the old pylogix file from old PC to new PC install and got it to work . I believe I remember the error was on line 288 of the eip.py file.  I think a divide  by zero error .

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bdamori** [comment]
I did have Micro800 set to true. If I get time to reinstall newer version I’ll get you the version number and actual error. It was the newest version as of yesterday or the day before.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bdamori** [comment]
The version I’m using that works is
__version_info__ = (0, 5, 1) I downloaded this around Oct 1 2019
When I look at what is on GITHUB now it is __version_info__ = (0, 5, 0)
I believe that this version  does not work.  Like I said I’ll try and retest next week.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kodaman2** [comment]
Thanks for the info. If the error is at line 288 then the bug could be line 1542 since you mentioned a divide between by zero error.

If you have time to confirm with a screenshot that would be great. In the readme you can see how to install with pip by versions. Just go on releases and go down the line until strings work.

**Comment by kodaman2** [comment]
Version 0.5.1 is not from this repo it was a fork and that guy changed the version but his code hasn't been merged, @dmroeder we really need to do something about that rogue repo, either way use the releases from this repo and install with pip as mentioned previously. My guess is that 0.4.13 or 12 will work fine.

**Comment by bdamori** [comment]
Thanks I’ll try one of those version .

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bdamori** [comment]
HI,
Neither   0.5.0 or 0.4.13 versions worked for me. Version 0.4.12 did work fine.

Below is the errors from the 2 versions that did not work.
Traceback (most recent call last):
  File "/home/linaro/Desktop/micro.py", line 8, in <module>
    comm.Write('Outbound','Have a Mark')
  File "/home/linaro/.local/lib/python3.7/site-packages/pylogix/eip.py", line 104, in Write
    return self._writeTag(tag, value, datatype)
  File "/home/linaro/.local/lib/python3.7/site-packages/pylogix/eip.py", line 291, in _writeTag
    writeData = self._convert_write_data(b, dataType, writeData)
  File "/home/linaro/.local/lib/python3.7/site-packages/pylogix/eip.py", line 1498, in _convert_write_data
    limit = int(space_for_payload / bytes_per_value)
ZeroDivisionError: division by zero

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dmroeder** [comment]
Interesting, I'll take a look.  Can you copy/paste the exact print out of the error?  Unfortunately, I no longer have my Micro820 PLC, or I would test it myself.

**Comment by bdamori** [comment]
I did past the errors on last email

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bdamori** [comment]
Let me know if/when you get newer versions fixed . I’ll try and run them.

Thanks
Bernie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dmroeder** [comment]
Haha, sorry, I'm having a hard time today apparently :)

**Comment by kodaman2** [comment]
> Haha, sorry, I'm having a hard time today apparently :)

Tbh is an odd format when you reply from emails lol. I'm having hard time reading the responses too.

**Comment by dmroeder** [comment]
I know what the problem is.  I'll email you something to test if you don't mind...

**Comment by bdamori** [comment]
Sure that’s fine

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bdamori** [comment]
[eip.py_line1542.txt](https://github.com/dmroeder/pylogix/files/4007869/eip.py_line1542.txt)
I made a change to eip.py  on line 1542. I'm new to Python so this may not be the correct change but it worked.see attachment

**Comment by dmroeder** [comment]
I take it that the change I emailed you didn't work?

**Comment by bdamori** [comment]
I did not get/find your email (dmroeder).  . I thought I saw one and when I went back  the next day I could not find it. If you send it again I will test it.

**Comment by dmroeder** [comment]
I sent it again, hopefully it's not going into your spam.

**Comment by bdamori** [comment]
Thanks, Changing line 71 in eip.py fixes the issue

**Comment by dmroeder** [comment]
I finally got a moment to push the change.  That should take care of this one.  Thanks for your help and testing!
